version: '3'
web:
  image: nginx 
  volumes:
   - ./config/ctf.conf:/etc/nginx/conf.d/nginxSV.conf
   - ./public_html:/usr/share/nginx
  ports:
   - "8080:80"
  command: /bin/sh -c "/etc/nginx/conf.d/nginxSV.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
